LIB   := main
CLIBS := -I ../queue -I ../getopt -I ../Point -I ../kruskal \
		 -I ../grid -I ../pltree -I ../edge
INCLUDES := ../getopt/getopt.h ../queue/queue.h ../Point/Point.h \
			../grid/grid.h ../kruskal/kruskal.h

include ../compile.mk
